import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const generateSubmissionPDF = (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const filename = `submission_${data.assignmentId}_${Date.now()}.pdf`;
      const filepath = path.join(__dirname, "../../exe-temp/", filename);

      // Ensure directory exists
      const dir = path.dirname(filepath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      // Report title
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("ASSIGNMENT SUBMISSION REPORT", {
          align: "center",
        });

      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica").text("=".repeat(90), {
        align: "center",
      });

      doc.moveDown(0.8);
      doc.fontSize(11).font("Helvetica-Bold").text("SUBMISSION DETAILS", {
        underline: true,
      });

      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica");
      doc.text(`Class Code: ${data.classCode || "N/A"}`);
      doc.text(`Assignment Title: ${data.assignmentTitle || "N/A"}`);
      doc.text(`Description: ${data.assignmentDescription || "N/A"}`);
      if (data.sampleInput) {
        doc.text(`Sample Input: ${data.sampleInput}`);
      }
      if (data.sampleOutput) {
        doc.text(`Sample Output: ${data.sampleOutput}`);
      }
      doc.text(`Maximum Marks: ${data.maximumMarks ?? "N/A"}`);
      doc.text(`Submitted By: ${data.submittedBy || "N/A"}`);
      doc.text(
        `Submission Date: ${new Date(data.submissionDate || Date.now()).toLocaleString()}`,
      );

      // Source code
      doc.moveDown(0.8);
      doc.fontSize(11).font("Helvetica-Bold").text("SOURCE CODE", {
        underline: true,
      });

      doc.moveDown(0.3);
      doc.fontSize(9).font("Courier");
      data.code.split("\n").forEach((line) => {
        doc.text(line, {
          width: 500,
          lineBreak: true,
        });
      });

      // AI Evaluation
      doc.addPage();
      doc.fontSize(11).font("Helvetica-Bold").text("AI EVALUATION", {
        underline: true,
      });

      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica");
      doc.text(`Category: ${data.aiEvaluation?.category || "N/A"}`);
      doc.text(
        `Score: ${typeof data.aiEvaluation?.score === "number" ? `${data.aiEvaluation.score} / 10` : "N/A"}`,
      );
      doc.moveDown(0.2);
      doc.font("Helvetica-Bold").text("Feedback:");
      doc
        .font("Helvetica")
        .text(data.aiEvaluation?.feedback || "No feedback provided", {
          width: 500,
        });

      if (data.aiEvaluation?.weaknesses?.length) {
        doc.moveDown(0.2);
        doc.font("Helvetica-Bold").text("Weaknesses:");
        doc.font("Helvetica");
        data.aiEvaluation.weaknesses.forEach((weakness) => {
          doc.text(`• ${weakness}`);
        });
      }

      // Assessment Results
      doc.moveDown(0.8);
      doc.fontSize(11).font("Helvetica-Bold").text("ASSESSMENT RESULTS", {
        underline: true,
      });

      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica");
      const assessmentCompleted = data.assessment?.completed === true;
      const mcqCount = data.aiEvaluation?.mcqs?.length || 0;
      doc.text(`Assessment Completed: ${assessmentCompleted ? "Yes" : "No"}`);
      doc.text(
        `MCQ Score: ${assessmentCompleted ? `${data.assessment.score} / ${mcqCount}` : "N/A"}`,
      );

      // Footer
      doc.moveDown(1.2);
      doc.fontSize(8).font("Helvetica").text("Generated by Code-CoLAB", {
        align: "center",
        opacity: 0.7,
      });

      doc.end();

      stream.on("finish", () => {
        resolve(filepath);
      });

      stream.on("error", (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};
