import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const generateSubmissionPDF = (data) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const filename = `submission_${data.assignmentId}_${Date.now()}.pdf`;
      const filepath = path.join(__dirname, "../../exe-temp/", filename);

      // Ensure directory exists
      const dir = path.dirname(filepath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      const stream = fs.createWriteStream(filepath);

      doc.pipe(stream);

      // Title
      doc.fontSize(20).font("Helvetica-Bold").text("Assignment Submission Report", {
        align: "center",
      });

      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica").text("=" .repeat(100), {
        align: "center",
      });

      doc.moveDown(0.8);

      // Header Information
      doc.fontSize(11).font("Helvetica-Bold").text("SUBMISSION DETAILS", {
        underline: true,
      });

      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica");

      const headerInfo = [
        { label: "Class Code:", value: data.classCode || "N/A" },
        { label: "Assignment Title:", value: data.assignmentTitle || "N/A" },
        { label: "Submitted By:", value: data.submittedBy || "N/A" },
        { label: "Submission Date:", value: new Date().toLocaleString() },
      ];

      headerInfo.forEach((item) => {
        doc.text(`${item.label} ${item.value}`);
      });

      // Students in Room
      if (data.studentsInRoom && data.studentsInRoom.length > 0) {
        doc.moveDown(0.5);
        doc.fontSize(11).font("Helvetica-Bold").text("TEAM MEMBERS", {
          underline: true,
        });
        doc.moveDown(0.3);
        doc.fontSize(10).font("Helvetica");
        data.studentsInRoom.forEach((student, index) => {
          doc.text(`${index + 1}. ${student}`);
        });
      }

      // Code Section
      doc.moveDown(0.8);
      doc.fontSize(11).font("Helvetica-Bold").text("SOURCE CODE", {
        underline: true,
      });

      doc.moveDown(0.3);
      doc.fontSize(9).font("Courier");

      const codeLines = data.code.split("\n");
      const maxLinesPerPage = 30;

      codeLines.forEach((line, index) => {
        if (index > 0 && index % maxLinesPerPage === 0) {
          doc.addPage();
        }
        const lineNumber = (index + 1).toString().padStart(3, " ");
        doc.text(`${lineNumber} | ${line}`, { width: 500 });
      });

      // Output Comparison Section
      doc.addPage();
      doc.fontSize(11).font("Helvetica-Bold").text("EXECUTION RESULTS", {
        underline: true,
      });

      doc.moveDown(0.5);

      // Expected Output
      doc.fontSize(10).font("Helvetica-Bold").text("Expected Output:");
      doc.fontSize(9).font("Courier");
      doc.text(data.expectedOutput || "No expected output provided", {
        width: 500,
        bg: "f0f0f0",
      });

      doc.moveDown(0.5);

      // Actual Output
      doc.fontSize(10).font("Helvetica-Bold").text("Actual Output:");
      doc.fontSize(9).font("Courier");

      const outputColor = data.outputMatches ? "#28a745" : "#dc3545";
      doc
        .fillColor(outputColor)
        .text(data.output || "No output generated", {
          width: 500,
        });

      doc.fillColor("black");

      doc.moveDown(0.5);

      // Validation Status
      const statusBg = data.outputMatches ? "#d4edda" : "#f8d7da";
      const statusText = data.outputMatches
        ? "✓ OUTPUT MATCHES EXPECTED"
        : "✗ OUTPUT DOES NOT MATCH EXPECTED";

      doc.moveDown(0.3);
      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text(statusText, {
          align: "center",
          bg: statusBg,
          padding: 10,
        });

      // Footer
      doc.moveDown(1);
      doc
        .fontSize(8)
        .font("Helvetica")
        .text("Generated by coLAB - Collaborative Code Learning Platform", {
          align: "center",
          color: "#999999",
        });

      doc.end();

      stream.on("finish", () => {
        resolve(filepath);
      });

      stream.on("error", (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};
